#!/usr/bin/env bash

. .version
sudo apt-get install jq
sudo jq --arg version "$VERSION" '.version=$VERSION' blueprint.json > blueprint_edit.json && mv blueprint_edit.json blueprint.json
git add .
git commit -m 'update blueprint version $VERSION [skip ci]'
